package com.example.model;
// Generated Apr 18, 2017 6:49:25 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "Redouane")
public class Client implements java.io.Serializable {

	private Integer id;
	private String name;
	private String phone;
	private String adresse;
	private String number;
	private Set<User> users = new HashSet<User>(0);
	private Set<Meter> meters = new HashSet<Meter>(0);

	public Client() {
	}

	public Client(String name, String phone, String adresse, String number) {
		this.name = name;
		this.phone = phone;
		this.adresse = adresse;
		this.number = number;
	}

	public Client(String name, String phone, String adresse, String number, Set<User> users, Set<Meter> meters) {
		this.name = name;
		this.phone = phone;
		this.adresse = adresse;
		this.number = number;
		this.users = users;
		this.meters = meters;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", nullable = false, length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "adresse", nullable = false, length = 250)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "number", nullable = false, length = 15)
	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_client", catalog = "Redouane", joinColumns = {
			@JoinColumn(name = "id_client", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_user", nullable = false, updatable = false) })
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<Meter> getMeters() {
		return this.meters;
	}

	public void setMeters(Set<Meter> meters) {
		this.meters = meters;
	}

}
