package com.example.model;
// Generated Apr 18, 2017 6:49:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consumption generated by hbm2java
 */
@Entity
@Table(name = "consumption", catalog = "Redouane")
public class Consumption implements java.io.Serializable {

	private Integer id;
	private Meter meter;
	private Date day;
	private float heuresPleines;
	private float heuresPointes;
	private float heuresCreuses;
	private float indexDay;

	public Consumption() {
	}

	public Consumption(Meter meter, Date day, float heuresPleines, float heuresPointes, float heuresCreuses,
			float indexDay) {
		this.meter = meter;
		this.day = day;
		this.heuresPleines = heuresPleines;
		this.heuresPointes = heuresPointes;
		this.heuresCreuses = heuresCreuses;
		this.indexDay = indexDay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_meter", nullable = false)
	public Meter getMeter() {
		return this.meter;
	}

	public void setMeter(Meter meter) {
		this.meter = meter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "day", nullable = false, length = 10)
	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	@Column(name = "heures_pleines", nullable = false, precision = 12, scale = 0)
	public float getHeuresPleines() {
		return this.heuresPleines;
	}

	public void setHeuresPleines(float heuresPleines) {
		this.heuresPleines = heuresPleines;
	}

	@Column(name = "heures_pointes", nullable = false, precision = 12, scale = 0)
	public float getHeuresPointes() {
		return this.heuresPointes;
	}

	public void setHeuresPointes(float heuresPointes) {
		this.heuresPointes = heuresPointes;
	}

	@Column(name = "heures_creuses", nullable = false, precision = 12, scale = 0)
	public float getHeuresCreuses() {
		return this.heuresCreuses;
	}

	public void setHeuresCreuses(float heuresCreuses) {
		this.heuresCreuses = heuresCreuses;
	}

	@Column(name = "index_day", nullable = false, precision = 12, scale = 0)
	public float getIndexDay() {
		return this.indexDay;
	}

	public void setIndexDay(float indexDay) {
		this.indexDay = indexDay;
	}

}
