package com.example.model;
// Generated Apr 18, 2017 6:49:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Validity generated by hbm2java
 */
@Entity
@Table(name = "validity", catalog = "Redouane")
public class Validity implements java.io.Serializable {

	private Integer id;
	private Parameter parameter;
	private Date startDate;
	private Date endDate;
	private double value;

	public Validity() {
	}

	public Validity(Parameter parameter, Date startDate, Date endDate, double value) {
		this.parameter = parameter;
		this.startDate = startDate;
		this.endDate = endDate;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_parameter", nullable = false)
	public Parameter getParameter() {
		return this.parameter;
	}

	public void setParameter(Parameter parameter) {
		this.parameter = parameter;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start_date", nullable = false, length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end_date", nullable = false, length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "value", nullable = false, precision = 22, scale = 0)
	public double getValue() {
		return this.value;
	}

	public void setValue(double value) {
		this.value = value;
	}

}
